[package]
name = "golangci-lint"
description = "Fast linters runner for Go"
homepage = "https://golangci-lint.run/"
license = "GPL-3.0-only"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "golangci/golangci-lint"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = ["go"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
