[package]
name = "asdf"
description = "Extendable version manager with support for Ruby, Node.js, Erlang & more"
homepage = "https://asdf-vm.com/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "asdf-vm/asdf"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
