[package]
name = "ninja"
description = "Small build system for use with gyp or CMake"
homepage = "https://ninja-build.org/"
license = "Apache-2.0"
tags = ["build-tool", "development"]

[discovery]
ports = "ninja"

[assets]
skip_checksums = true

[dependencies]
runtime = []
build = []
optional = []

[install]
bin = ["ninja"]

[hints]
post_install = "ninja build system is now available."
