[package]
name = "bandwhich"
description = "Terminal bandwidth utilization tool"
homepage = "https://github.com/imsnif/bandwhich"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "imsnif/bandwhich"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
