[package]
name = "bat"
description = "Clone of cat(1) with syntax highlighting and Git integration"
homepage = "https://github.com/sharkdp/bat"
license = "Apache-2.0 OR MIT"
tags = ["imported", "homebrew"]

[discovery]
github = "sharkdp/bat"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
