[package]
name = "termshot"
description = "Creates screenshots based on terminal command output"
homepage = "https://github.com/homeport/termshot"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "homeport/termshot"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
