[package]
name = "terraform"
description = "Infrastructure as Code tool for building, changing, and versioning infrastructure"
homepage = "https://www.terraform.io/"
license = "BUSL-1.1"
tags = ["iac", "hashicorp", "ports"]

[discovery]
ports = "terraform"

[assets]
skip_checksums = false

[dependencies]

[install]
bin = ["terraform"]

[hints]
