[package]
name = "lf"
description = "Terminal file manager"
homepage = "https://godoc.org/github.com/gokcehan/lf"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "gokcehan/lf"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
