[package]
name = "rclone"
description = "Rsync for cloud storage"
homepage = "https://rclone.org/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "rclone/rclone"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
