[package]
name = "yazi"
description = "Blazing fast terminal file manager written in Rust, based on async I/O"
homepage = "https://github.com/sxyazi/yazi"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "sxyazi/yazi"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
