[package]
name = "fx"
description = "Terminal JSON viewer"
homepage = "https://fx.wtf"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "antonmedv/fx"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
