[package]
name = "fontconfig"
description = "Font configuration and customization library"
homepage = "https://www.freedesktop.org/wiki/Software/fontconfig/"
license = "MIT"
tags = ["library", "fonts"]

[discovery]
ports = "fontconfig"

[assets]
skip_checksums = true

[dependencies]
runtime = ["freetype", "expat"]
build = ["meson", "ninja", "gperf"]
optional = []

[install]
bin = ["fc-cache", "fc-list", "fc-match"]
lib = ["libfontconfig.a"]
include = ["fontconfig/fontconfig.h"]

[hints]
post_install = "fontconfig library is now available."
