[package]
name = "lsd"
description = "Clone of ls with colorful output, file type icons, and more"
homepage = "https://github.com/lsd-rs/lsd"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "lsd-rs/lsd"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
