[package]
name = "git-town"
description = "High-level command-line interface for Git"
homepage = "https://www.git-town.com/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "git-town/git-town"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
