[package]
name = "gitui"
description = "Blazing fast terminal-ui for git written in rust"
homepage = "https://github.com/gitui-org/gitui"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "gitui-org/gitui"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = ["openssl@3.5"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
