[package]
name = "biome"
description = "Toolchain of the web"
homepage = "https://biomejs.dev/"
license = "Apache-2.0 OR MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "biomejs/biome"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
