[package]
name = "pango"
description = "Text layout and rendering library"
homepage = "https://pango.gnome.org/"
license = "LGPL-2.1-or-later"
tags = ["library", "text", "gnome"]

[discovery]
ports = "pango"

[assets]
skip_checksums = true

[dependencies]
runtime = ["glib", "harfbuzz", "freetype", "fontconfig", "cairo", "fribidi"]
build = ["meson", "ninja"]
optional = []

[install]
lib = ["libpango-1.0.a", "libpangocairo-1.0.a", "libpangoft2-1.0.a"]
include = ["pango-1.0/pango/pango.h"]

[hints]
post_install = "pango library is now available."
