[package]
name = "pastel"
description = "Command-line tool to generate, analyze, convert and manipulate colors"
homepage = "https://github.com/sharkdp/pastel"
license = "Apache-2.0 OR MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "sharkdp/pastel"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
