[package]
name = "caddy"
description = "Powerful, enterprise-ready, open source web server with automatic HTTPS"
homepage = "https://caddyserver.com/"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "caddyserver/caddy"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
