[package]
name = "nushell"
description = "Modern shell for the GitHub era"
homepage = "https://www.nushell.sh"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "nushell/nushell"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[dependencies]
runtime = ["openssl@3"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
