[package]
name = "qsv"
description = "Ultra-fast CSV data-wrangling toolkit"
homepage = "https://qsv.dathere.com/"
license = "MIT OR Unlicense"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "dathere/qsv"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
