[package]
name = "colima"
description = "Container runtimes on MacOS (and Linux) with minimal setup"
homepage = "https://github.com/abiosoft/colima/blob/main/README.md"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "abiosoft/colima"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = ["lima"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
