[package]
name = "goreleaser"
description = "Deliver Go binaries as fast and easily as possible"
homepage = "https://goreleaser.com/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "goreleaser/goreleaser"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
