[package]
name = "sccache"
description = "Used as a compiler wrapper and avoids compilation when possible"
homepage = "https://github.com/mozilla/sccache"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "mozilla/sccache"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
