[package]
name = "k9s"
description = "Kubernetes CLI To Manage Your Clusters In Style!"
homepage = "https://k9scli.io/"
license = "Apache-2.0"
tags = ["imported", "homebrew"]

[discovery]
github = "derailed/k9s"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
bin = ["k9s"]
lib = []
include = []

[hints]
post_install = ""
