[package]
name = "syft"
description = "CLI for generating a Software Bill of Materials from container images"
homepage = "https://github.com/anchore/syft"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "anchore/syft"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
