[package]
name = "syncthing"
description = "Open source continuous file synchronization application"
homepage = "https://syncthing.net/"
license = "MPL-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "syncthing/syncthing"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
