[package]
name = "cmake"
description = "Cross-platform make"
homepage = "https://cmake.org/"
license = "BSD-3-Clause"
tags = ["build-tool", "development"]

[discovery]
ports = "cmake"

[assets]
skip_checksums = true

[dependencies]
runtime = []
build = []
optional = []

[install]
bin = ["cmake", "ctest", "cpack"]

[hints]
post_install = "cmake, ctest, and cpack are now available."
