[package]
name = "cmake"
description = "Cross-platform make"
homepage = "https://www.cmake.org/"
license = "BSD-3-Clause"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "Kitware/CMake"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
