[package]
name = "lazysql"
description = "Cross-platform TUI database management tool"
homepage = "https://github.com/jorgerojas26/lazysql"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "jorgerojas26/lazysql"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
