[package]
name = "lazydocker"
description = "Lazier way to manage everything docker"
homepage = "https://github.com/jesseduffield/lazydocker"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "jesseduffield/lazydocker"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
