[package]
name = "opa"
description = "Open source, general-purpose policy engine"
homepage = "https://www.openpolicyagent.org"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "open-policy-agent/opa"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
