[package]
name = "openssl@3.5"
description = "Cryptography and SSL/TLS Toolkit"
homepage = "https://www.openssl.org/"
license = "Apache-2.0"
tags = ["library", "security"]

[discovery]
ports = "openssl@3.5"

[assets]
skip_checksums = true

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = ["libssl.a", "libcrypto.a"]
include = ["openssl"]

[hints]
post_install = "OpenSSL 3 headers and static libraries have been installed."
