[package]
name = "csvlens"
description = "Command-line csv viewer"
homepage = "https://github.com/YS-L/csvlens"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "YS-L/csvlens"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
