[package]
name = "fastfetch"
description = "Like neofetch, but much faster because written mostly in C"
homepage = "https://github.com/fastfetch-cli/fastfetch"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "fastfetch-cli/fastfetch"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = ["yyjson"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
