[package]
name = "gmp"
description = "The GNU Multiple Precision Arithmetic Library"
homepage = "https://gmplib.org/"
license = "LGPL-3.0-or-later OR GPL-2.0-or-later"
tags = ["library", "math"]

[discovery]
github = "aleaxit/gmp-release"
tag_pattern = "v{{version}}"

[assets]
skip_checksums = true

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = ["libgmp.a"]
include = ["gmp.h"]

[hints]
post_install = "GMP headers and static library have been installed."
