[package]
name = "starship"
description = "Cross-shell prompt for astronauts"
homepage = "https://starship.rs/"
license = "ISC"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "starship/starship"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
