[package]
name = "fd"
description = "Simple, fast and user-friendly alternative to find"
homepage = "https://github.com/sharkdp/fd"
license = "Apache-2.0 OR MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "sharkdp/fd"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
