[package]
name = "crane"
description = "Tool for interacting with remote images and registries"
homepage = "https://github.com/google/go-containerregistry"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "google/go-containerregistry"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
