[package]
name = "glib"
description = "GNOME low-level core library"
homepage = "https://docs.gtk.org/glib/"
license = "LGPL-2.1-or-later"
tags = ["library", "gnome"]

[discovery]
ports = "glib"

[assets]
skip_checksums = true

[dependencies]
runtime = ["libffi", "pcre2", "gettext", "zlib"]
build = ["meson", "ninja"]
optional = []

[install]
bin = ["glib-compile-schemas", "glib-compile-resources"]
lib = ["libglib-2.0.a", "libgobject-2.0.a", "libgio-2.0.a"]
include = ["glib-2.0/glib.h"]

[hints]
post_install = "glib library is now available."
