[package]
name = "libgit2"
description = "A portable, pure C implementation of the Git core methods"
homepage = "https://libgit2.org/"
license = "GPL-2.0-only WITH GCC-exception-2.0"
tags = ["library", "git"]

[discovery]
github = "libgit2/libgit2"
tag_pattern = "v{{version}}"

[assets]
skip_checksums = true

[dependencies]
runtime = ["openssl@3.5"]
build = []
optional = []

[install]
lib = ["libgit2.a"]
include = ["git2.h"]

[hints]
post_install = "libgit2 headers and static library have been installed."
