[package]
name = "libyaml"
description = "YAML Parser"
homepage = "https://github.com/yaml/libyaml"
license = "MIT"
tags = ["imported", "homebrew"]

[discovery]
ports = "libyaml"

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
