[package]
name = "trivy"
description = "Vulnerability scanner for container images, file systems, and Git repos"
homepage = "https://trivy.dev/"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "aquasecurity/trivy"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
