[package]
name = "trufflehog"
description = "Find and verify credentials"
homepage = "https://trufflesecurity.com/"
license = "AGPL-3.0-only"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "trufflesecurity/trufflehog"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
