[package]
name = "diskus"
description = "Minimal, fast alternative to 'du -sh'"
homepage = "https://github.com/sharkdp/diskus"
license = "Apache-2.0 OR MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "sharkdp/diskus"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
