[package]
name = "miller"
description = "Like sed, awk, cut, join & sort for name-indexed data such as CSV"
homepage = "https://github.com/johnkerl/miller"
license = "BSD-2-Clause"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "johnkerl/miller"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
