[package]
name = "deno"
description = "Secure runtime for JavaScript and TypeScript"
homepage = "https://deno.com/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "denoland/deno"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = [
    "little-cms2",
    "sqlite",
]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
