[package]
name = "python@3.14"
description = "Interpreted, high-level, general-purpose programming language (3.14.x)"
homepage = "https://www.python.org/"
license = "Python-2.0"
tags = ["language", "interpreter"]

[discovery]
ports = "python@3.14"

[assets]
skip_checksums = true

[dependencies]
runtime = ["openssl@3.5", "sqlite", "zlib", "xz", "libffi", "readline", "ncurses"]

[install]
bin = ["python3", "pip3"]

[hints]
post_install = "Python 3.14.x has been built from source and installed in the APL Sysroot."
