[package]
name = "helm"
description = "Kubernetes package manager"
homepage = "https://helm.sh/"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "helm/helm"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
