[package]
name = "railway"
description = "Develop and deploy code with zero configuration"
homepage = "https://railway.com/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "railwayapp/cli"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
