[package]
name = "xz"
description = "General-purpose data compression software with high compression ratio"
homepage = "https://tukaani.org/xz/"
license = "Public Domain"
tags = ["library", "compression"]

[discovery]
ports = "xz"

[assets]
skip_checksums = true

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = ["liblzma.a"]
include = ["lzma.h"]

[hints]
post_install = "xz (lzma) headers and static library have been installed."
