[package]
name = "gdu"
description = "Disk usage analyzer with console interface written in Go"
homepage = "https://github.com/dundee/gdu"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "dundee/gdu"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
