[package]
name = "charm"
description = "Tool for managing Juju Charms"
homepage = "https://github.com/juju/charmstore-client"
license = "GPL-3.0-only"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "juju/charmstore-client"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
