[package]
name = "choose"
description = "Make choices on the command-line"
homepage = "https://github.com/geier/choose"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "geier/choose"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = ["python"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
