[package]
name = "choose"
description = "Make choices on the command-line"
homepage = "https://github.com/geier/choose"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "geier/choose"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[dependencies]
runtime = ["python@3.13"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
