[package]
name = "age"
description = "Simple, modern, secure file encryption"
homepage = "https://github.com/FiloSottile/age"
license = "BSD-3-Clause"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "FiloSottile/age"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
