[package]
name = "yq"
description = "Process YAML, JSON, XML, CSV and properties documents from the CLI"
homepage = "https://github.com/mikefarah/yq"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "mikefarah/yq"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
