[package]
name = "bottom"
description = "Yet another cross-platform graphical process/system monitor"
homepage = "https://clementtsang.github.io/bottom/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "ClementTsang/bottom"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
