[package]
name = "gping"
description = "Ping, but with a graph"
homepage = "https://github.com/orf/gping"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "orf/gping"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
