[package]
name = "flyctl"
description = "Command-line tools for fly.io services"
homepage = "https://fly.io"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "superfly/flyctl"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
