[package]
name = "viddy"
description = "Modern watch command"
homepage = "https://github.com/sachaos/viddy"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "sachaos/viddy"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
