[package]
name = "slides"
description = "Terminal based presentation tool"
homepage = "https://maaslalani.com/slides/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "maaslalani/slides"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
