[package]
name = "slsa-verifier"
description = "Verify provenance from SLSA compliant builders"
homepage = "https://github.com/slsa-framework/slsa-verifier"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "slsa-framework/slsa-verifier"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
