[package]
name = "fzf"
description = "Command-line fuzzy finder written in Go"
homepage = "https://github.com/junegunn/fzf"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "junegunn/fzf"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
