[package]
name = "pixman"
description = "Low-level pixel manipulation library"
homepage = "http://pixman.org/"
license = "MIT"
tags = ["library", "graphics"]

[discovery]
ports = "pixman"

[assets]
skip_checksums = true

[dependencies]
runtime = []
build = ["meson", "ninja"]
optional = []

[install]
lib = ["libpixman-1.a"]
include = ["pixman-1/pixman.h"]

[hints]
post_install = "pixman library is now available."
