[package]
name = "neovim"
description = "Ambitious Vim-fork focused on extensibility and agility"
homepage = "https://neovim.io/"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "neovim/neovim"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = [
    "tree-sitter@0.25",
    "gettext",
    "libuv",
    "lpeg",
    "luajit",
    "luv",
    "unibilium",
    "utf8proc",
]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
