[package]
name = "atuin"
description = "Improved shell history for zsh, bash, fish and nushell"
homepage = "https://atuin.sh/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "atuinsh/atuin"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
