[package]
name = "cloudflared"
description = "Cloudflare Tunnel client (formerly Argo Tunnel)"
homepage = "https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-tunnel/"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "cloudflare/cloudflared"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
