[package]
name = "zellij"
description = "Pluggable terminal workspace, with terminal multiplexer as the base feature"
homepage = "https://zellij.dev"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "zellij-org/zellij"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = ["openssl@3"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
