[package]
name = "ripgrep"
description = "Search tool like grep and The Silver Searcher"
homepage = "https://github.com/BurntSushi/ripgrep"
license = "Unlicense"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "BurntSushi/ripgrep"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = ["pcre2"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
