[package]
name = "grex"
description = "Command-line tool for generating regular expressions"
homepage = "https://github.com/pemistahl/grex"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "pemistahl/grex"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
