[package]
name = "just"
description = "Handy way to save and run project-specific commands"
homepage = "https://github.com/casey/just"
license = "CC0-1.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "casey/just"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
