[package]
name = "hyperfine"
description = "Command-line benchmarking tool"
homepage = "https://github.com/sharkdp/hyperfine"
license = "Apache-2.0 OR MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "sharkdp/hyperfine"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
