[package]
name = "air"
description = "Fast and opinionated formatter for R code"
homepage = "https://github.com/posit-dev/air"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "posit-dev/air"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
