[package]
name = "duf"
description = "Disk Usage/Free Utility - a better 'df' alternative"
homepage = "https://github.com/muesli/duf"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "muesli/duf"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
