[package]
name = "dust"
description = "More intuitive version of du in rust"
homepage = "https://github.com/bootandy/dust"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "bootandy/dust"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
