[package]
name = "dbmate"
description = "Lightweight, framework-agnostic database migration tool"
homepage = "https://github.com/amacneil/dbmate"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "amacneil/dbmate"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
