[package]
name = "skaffold"
description = "Easy and Repeatable Kubernetes Development"
homepage = "https://skaffold.dev/"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "GoogleContainerTools/skaffold"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
