[package]
name = "gitleaks"
description = "Audit git repos for secrets"
homepage = "https://gitleaks.io/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "gitleaks/gitleaks"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
