[package]
name = "dasel"
description = "JSON, YAML, TOML, XML, and CSV query and modification tool"
homepage = "https://github.com/TomWright/dasel"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "TomWright/dasel"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
