[package]
name = "mods"
description = "AI on the command-line"
homepage = "https://github.com/charmbracelet/mods"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "charmbracelet/mods"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
