[package]
name = "dprint"
description = "Pluggable and configurable code formatting platform written in Rust"
homepage = "https://dprint.dev/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "dprint/dprint"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = ["xz"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
