[package]
name = "osv-scanner"
description = "Vulnerability scanner which uses the OSV database"
homepage = "https://github.com/google/osv-scanner"
license = "Apache-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "google/osv-scanner"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
