[package]
name = "podman"
description = "Tool for managing OCI containers and pods"
homepage = "https://podman.io/"
license = "Apache-2.0 AND GPL-3.0-or-later"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "containers/podman"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
