[package]
name = "onefetch"
description = "Command-line Git information tool"
homepage = "https://onefetch.dev/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "o2sh/onefetch"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[dependencies]
runtime = ["zstd"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
