[package]
name = "sops"
description = "Editor of encrypted files"
homepage = "https://getsops.io/"
license = "MPL-2.0"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "getsops/sops"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[dependencies]
runtime = []
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
