[package]
name = "jq"
description = "Lightweight and flexible command-line JSON processor"
homepage = "https://jqlang.github.io/jq/"
license = "MIT"
tags = [
    "imported",
    "homebrew",
]

[discovery]
github = "jqlang/jq"
tag_pattern = "{{version}}"
include_prereleases = false

[assets]
skip_checksums = false

[assets.arm64-macos]
suffix = "aarch64-apple-darwin"

[assets.x86_64-macos]
suffix = "x86_64-apple-darwin"

[dependencies]
runtime = ["oniguruma"]
build = []
optional = []

[install]
lib = []
include = []

[hints]
post_install = ""
